export default () => ({
  database: process.env.DATABASE,
  NODE_ENV: process.env.NODE_ENV,
  CACHE_TTL: process.env.CACHE_TTL,
  JWT_SECRET: process.env.JWT_SECRET,
  JWT_EXPIRES_IN: process.env.JWT_EXPIRES_IN,
  JWT_REFRESH_SECRET: process.env.JWT_REFRESH_SECRET,
  JWT_REFRESH_EXPIRES_IN: process.env.JWT_REFRESH_EXPIRES_IN,
  ACCESS_TOKEN_COOKIE_EXPIRES_IN: process.env.ACCESS_TOKEN_COOKIE_EXPIRES_IN,
  REFRESH_TOKEN_COOKIE_EXPIRES_IN: process.env.REFRESH_TOKEN_COOKIE_EXPIRES_IN,
  OPENAI_API_KEY: process.env.OPENAI_API_KEY,
  OPENAI_MODEL: process.env.OPENAI_MODEL,
});
